#!/usr/bin/env python3
"""Verify generated font tables without modifying the working tree."""

from __future__ import annotations

import filecmp
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def run(*args: str) -> None:
    subprocess.run([sys.executable, *args], cwd=ROOT, check=True)


def format_generated(output: Path) -> None:
    subprocess.run(["gofmt", "-w", *map(str, output.glob("*.go"))], cwd=ROOT, check=True)


def main() -> None:
    with tempfile.TemporaryDirectory(prefix="go-playa-generated-") as directory:
        output = Path(directory)
        run("scripts/generate_glyphlist.py", "--package", "fontdata", "--output", str(output / "glyphlist_generated.go"))
        run(
            "scripts/generate_core14_metrics.py",
            "--package",
            "fontdata",
            "--output",
            str(output / "standard_metrics_generated.go"),
        )
        run("scripts/generate_cff_resources.py", "--package", "fontdata", "--output-dir", str(output))
        run("scripts/generate_macroman_encoding.py", "--package", "fontdata", "--output", str(output / "macroman_encoding_generated.go"))
        run("scripts/generate_winansi_encoding.py", "--package", "fontdata", "--output", str(output / "winansi_encoding_generated.go"))
        run("scripts/generate_symbol_encoding.py", "--package", "fontdata", "--output", str(output / "symbol_encoding_generated.go"))
        run(
            "scripts/generate_zapfdingbats_encoding.py", "--package", "fontdata",
            "--output",
            str(output / "zapfdingbats_encoding_generated.go"),
        )
        run("scripts/generate_macexpert_encoding.py", "--package", "fontdata", "--output", str(output / "macexpert_encoding_generated.go"))
        run("scripts/generate_ccitt_tables.py", "--output", str(output / "ccitt_tables_generated.go"))
        format_generated(output)

        generated = sorted(output.glob("*.go"))
        expected_names = {candidate.name for candidate in generated}
        mismatches = []
        fontdata_moved = {"glyphlist_generated.go", "standard_metrics_generated.go", "cff_standard_strings.go", "cff_predefined_charsets.go", "cff_encoding_generated.go", "macroman_encoding_generated.go", "winansi_encoding_generated.go", "symbol_encoding_generated.go", "zapfdingbats_encoding_generated.go", "macexpert_encoding_generated.go"}
        parser_moved = {"ccitt_tables_generated.go"}
        for candidate in generated:
            owner = "fontdata" if candidate.name in fontdata_moved else "parser" if candidate.name in parser_moved else "document"
            checked_in = ROOT / owner / candidate.name
            if not checked_in.is_file():
                mismatches.append(f"missing {checked_in}")
            elif not filecmp.cmp(candidate, checked_in, shallow=False):
                mismatches.append(f"out-of-date {checked_in}")
        for directory in (ROOT / "document", ROOT / "fontdata", ROOT / "parser"):
            for checked_in in sorted(directory.glob("*.go")):
                try:
                    header = checked_in.read_text(encoding="utf-8").splitlines()[0]
                except (OSError, IndexError):
                    continue
                if "Code generated by scripts/" in header and checked_in.name not in expected_names:
                    mismatches.append(f"obsolete {checked_in}")
        if mismatches:
            raise SystemExit("generated resource drift:\n" + "\n".join(mismatches))
        print(f"checked {len(generated)} generated font tables")


if __name__ == "__main__":
    main()
