#!/usr/bin/env python3
"""Generate the CCITT decode tables used by the mixed-mode PDF decoder."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def source_path() -> Path:
    result = subprocess.run(
        ["go", "mod", "download", "-json", "golang.org/x/image"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    module = json.loads(result.stdout)
    directory = module.get("Dir")
    if not directory:
        raise SystemExit("go mod download did not report the golang.org/x/image source directory")
    return Path(directory) / "ccitt" / "table.go"


def extract(source: str, name: str) -> str:
    match = re.search(rf"var {name} = \[\.\.\.\]\[2\]int16\{{(.*?)\n\}}", source, re.S)
    if not match:
        raise SystemExit(f"missing {name} in {source_path()}")
    return match.group(1)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=source_path())
    parser.add_argument("--output", type=Path, default=ROOT / "parser/ccitt_tables_generated.go")
    args = parser.parse_args()
    source = args.source.read_text()
    names = ("modeDecodeTable", "whiteDecodeTable", "blackDecodeTable")
    replacements = ("pdfparserCCITTModeDecodeTable", "pdfparserCCITTWhiteDecodeTable", "pdfparserCCITTBlackDecodeTable")
    chunks = ["// Code generated by scripts/generate_ccitt_tables.py; DO NOT EDIT.\n", "\npackage parser\n"]
    for name, replacement in zip(names, replacements):
        chunks.append(f"\nvar {replacement} = [...][2]int16{{{extract(source, name)}\n}}\n")
    args.output.write_text("".join(chunks))


if __name__ == "__main__":
    main()
