#!/usr/bin/env python3
"""Generate Go glyph tables from vendored Adobe source files."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def parse(source: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    for line_number, raw in enumerate(source.read_text(encoding="ascii").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        try:
            name, value = line.split(";", 1)
            codepoints = [int(part, 16) for part in value.split()]
        except ValueError as exc:
            raise ValueError(f"{source}:{line_number}: invalid glyph record") from exc
        if not name or any(not (0 <= codepoint <= 0x10FFFF) for codepoint in codepoints):
            raise ValueError(f"{source}:{line_number}: invalid glyph record")
        text = "".join(chr(codepoint) for codepoint in codepoints)
        if name in result and result[name] != text:
            raise ValueError(f"{source}:{line_number}: duplicate glyph {name}")
        result[name] = text
    return result


def string_literal(value: str) -> str:
    out = ['"']
    for char in value:
        codepoint = ord(char)
        if char == '"':
            out.append('\\"')
        elif char == "\\":
            out.append("\\\\")
        elif codepoint <= 0xFFFF:
            out.append(f"\\u{codepoint:04X}")
        else:
            out.append(f"\\U{codepoint:08X}")
    out.append('"')
    return "".join(out)


def generate(entries: dict[str, str], zapf_entries: dict[str, str], package: str) -> str:
    lines = [
        "// Code generated by scripts/generate_glyphlist.py; DO NOT EDIT.",
        "",
        f"package {package}",
        "",
        "// adobeGlyphText is the Adobe Glyph List mapping, including",
        "// glyph names that expand to multiple Unicode code points.",
        "var adobeGlyphText = map[string]string{",
    ]
    for name in sorted(entries):
        lines.append(f'\t"{name}": {string_literal(entries[name])},')
    lines.extend(["}", "", "// zapfDingbatsGlyphText is Adobe's ITC Zapf Dingbats Glyph List.", "var zapfDingbatsGlyphText = map[string]string{"])
    for name in sorted(zapf_entries):
        lines.append(f'\t"{name}": {string_literal(zapf_entries[name])},')
    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=ROOT / "scripts/data/glyphlist.txt")
    parser.add_argument("--zapf-input", type=Path, default=ROOT / "scripts/data/zapfdingbats.txt")
    parser.add_argument("--output", type=Path, default=ROOT / "fontdata/glyphlist_generated.go")
    parser.add_argument("--package", default="fontdata")
    args = parser.parse_args()
    args.output.write_text(generate(parse(args.input), parse(args.zapf_input), args.package), encoding="utf-8")


if __name__ == "__main__":
    main()
