#!/usr/bin/env python3
"""Generate the PDF ZapfDingbats encoding from the synchronized AFM."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
AFM = ROOT / "scripts/data/core14/ZapfDingbats.afm"
GLYPHLIST = ROOT / "scripts/data/zapfdingbats.txt"
OUTPUT = ROOT / "fontdata/zapfdingbats_encoding_generated.go"

PRIVATE_OVERRIDES = {
    128: "\uf8d7", 129: "\uf8d8", 130: "\uf8d9", 131: "\uf8da",
    132: "\uf8db", 133: "\uf8dc", 134: "\uf8dd", 135: "\uf8de",
    136: "\uf8df", 137: "\uf8e0", 138: "\uf8e1", 139: "\uf8e2",
    140: "\uf8e3", 141: "\uf8e4",
}


def glyphs() -> dict[str, str]:
    result = {}
    for line in GLYPHLIST.read_text(encoding="ascii").splitlines():
        if not line or line.startswith("#") or ";" not in line:
            continue
        name, values = line.split(";", 1)
        try:
            result[name] = "".join(chr(int(value, 16)) for value in values.split())
        except ValueError:
            continue
    return result


def rune_literal(value: str) -> str:
    code = ord(value)
    if value == "'":
        return "'\\''"
    if value == "\\":
        return "'\\\\'"
    if 0x20 <= code < 0x7f:
        return f"'{value}'"
    if code <= 0xffff:
        return f"'\\u{code:04x}'"
    return f"'\\U{code:08x}'"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--package", default="fontdata")
    args = parser.parse_args()
    names = glyphs()
    entries = {32: " "}
    for line in AFM.read_text(encoding="ascii").splitlines():
        if not line.startswith("C "):
            continue
        fields = {key: value.strip() for key, value in re.findall(r"([A-Z]+) ([^;]+)", line)}
        code = int(fields.get("C", "-1"))
        if 0 <= code <= 255:
            text = names.get(fields.get("N", ""), "")
            if len(text) == 1:
                entries[code] = text
    entries.update(PRIVATE_OVERRIDES)
    lines = [
        "// Code generated by scripts/generate_zapfdingbats_encoding.py; DO NOT EDIT.",
        "",
        f"package {args.package}",
        "",
        "var generatedZapfDingbatsEncoding = map[byte]rune{",
    ]
    for code, value in sorted(entries.items()):
        lines.append(f"\t{code}: {rune_literal(value)},")
    lines.extend(["}", ""])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
