#!/usr/bin/env python3
"""Generate the PDF Symbol encoding from the synchronized Core 14 AFM."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
AFM = ROOT / "scripts/data/core14/Symbol.afm"
AGL = ROOT / "scripts/data/glyphlist.txt"
OUTPUT = ROOT / "fontdata/symbol_encoding_generated.go"

OVERRIDES = {
	"Mu": "Μ",
	"registerserif": "®",
	"copyrightserif": "©",
	"trademarkserif": "™",
	"registersans": "®",
	"copyrightsans": "©",
	"trademarksans": "™",
	"integraltp": "⌠",
	"integralbt": "⌡",
}


def glyphs() -> dict[str, str]:
    result = {}
    for line in AGL.read_text(encoding="ascii").splitlines():
        if not line or line.startswith("#") or ";" not in line:
            continue
        name, values = line.split(";", 1)
        try:
            result[name] = "".join(chr(int(value, 16)) for value in values.split())
        except ValueError:
            continue
    return result


def symbol_encoding(names: dict[str, str]) -> dict[int, str]:
    result = {}
    for line in AFM.read_text(encoding="ascii").splitlines():
        if not line.startswith("C "):
            continue
        fields = {key: value.strip() for key, value in re.findall(r"([A-Z]+) ([^;]+)", line)}
        code = int(fields.get("C", "-1"))
        if code < 0 or code > 255:
            continue
        name = fields.get("N", "")
        text = OVERRIDES.get(name, names.get(name, ""))
        if len(text) == 1:
            result[code] = text
    return result


def rune_literal(value: str) -> str:
    code = ord(value)
    if value == "'":
        return "'\\''"
    if value == "\\":
        return "'\\\\'"
    if 0x20 <= code < 0x7f:
        return f"'{value}'"
    if code <= 0xffff:
        return f"'\\u{code:04x}'"
    return f"'\\U{code:08x}'"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--package", default="fontdata")
    args = parser.parse_args()
    entries = symbol_encoding(glyphs())
    lines = [
        "// Code generated by scripts/generate_symbol_encoding.py; DO NOT EDIT.",
        "",
        f"package {args.package}",
        "",
        "var generatedSymbolEncoding = map[byte]rune{",
    ]
    for code, value in sorted(entries.items()):
        lines.append(f"\t{code}: {rune_literal(value)},")
    lines.extend(["}", ""])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
