#!/usr/bin/env python3
"""Generate PDF MacRoman mappings from the codec plus ISO glyph assignments.

ISO 32000-1:2008 Annex D.2 notes 1 and 6 retain currency at octal 333
and duplicate space at octal 312, unlike the modern mac_roman codec.
Reference: https://opensource.adobe.com/dc-acrobat-sdk-docs/standards/pdfstandards/pdf/PDF32000_2008.pdf
"""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "fontdata/macroman_encoding_generated.go"


def rune_literal(value: str) -> str:
    code = ord(value)
    if value == "'":
        return "'\\''"
    if value == "\\":
        return "'\\\\'"
    if 0x20 <= code < 0x7f:
        return f"'{value}'"
    if code <= 0xffff:
        return f"'\\u{code:04x}'"
    return f"'\\U{code:08x}'"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--package", default="fontdata")
    args = parser.parse_args()
    entries = {}
    for code in range(0x80, 0x100):
        text = bytes([code]).decode("mac_roman")
        if len(text) == 1:
            entries[code] = text
    entries[0xca] = " "
    entries[0xdb] = "\u00a4"
    lines = [
        "// Code generated by scripts/generate_macroman_encoding.py; DO NOT EDIT.",
        "// Source: mac_roman codec with ISO 32000-1:2008 Annex D.2 glyph assignments.",
        "",
        f"package {args.package}",
        "",
        "var generatedMacRomanEncoding = map[byte]rune{",
    ]
    for code, value in entries.items():
        lines.append(f"\t{code}: {rune_literal(value)},")
    lines.extend(["}", ""])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
