#!/usr/bin/env python3
"""Generate PDF MacExpertEncoding from the pinned Apache PDFBox source."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "scripts/data/pdfbox/MacExpertEncoding.java"
OUTPUT = ROOT / "fontdata/macexpert_encoding_generated.go"
ENTRY = re.compile(r'\{(0[0-7]+),\s*"([A-Za-z0-9_.]+)"\}')


def read_encoding(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    start = text.find("MAC_EXPERT_ENCODING_TABLE = {")
    end = text.find("};", start + 1)
    if start < 0 or end < 0:
        raise ValueError(f"{path}: MacExpertEncoding table not found")
    names = [".notdef"] * 256
    seen = set()
    for match in ENTRY.finditer(text[start:end]):
        code = int(match.group(1), 8)
        if code > 255 or code in seen:
            raise ValueError(f"{path}: invalid or duplicate character code {code}")
        seen.add(code)
        names[code] = match.group(2)
    if len(seen) != 165:
        raise ValueError(f"{path}: expected 165 defined entries, found {len(seen)}")
    return names


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=SOURCE)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--package", default="fontdata")
    args = parser.parse_args()
    names = read_encoding(args.source)
    lines = [
        "// Code generated by scripts/generate_macexpert_encoding.py; DO NOT EDIT.",
        "// MacExpertEncoding: Modified/translated from Apache PDFBox material; Apache-2.0.",
        "// See NOTICE, THIRD_PARTY_LICENSES, and scripts/data/pdfbox/LICENSE.txt.",
        "",
        f"package {args.package}",
        "",
        "// MacExpertEncoding glyph names, indexed by PDF character code.",
        "var MacExpertEncoding = [...]string{",
    ]
    for name in names:
        lines.append(f'\t"{name}",')
    lines.extend(["}", ""])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
