#!/usr/bin/env python3
"""Generate standard PDF font metrics from Core14 AFM files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


FONT_NAMES = (
    "Courier",
    "Courier-Bold",
    "Courier-BoldOblique",
    "Courier-Oblique",
    "Helvetica",
    "Helvetica-Bold",
    "Helvetica-BoldOblique",
    "Helvetica-Oblique",
    "Symbol",
    "Times-Bold",
    "Times-BoldItalic",
    "Times-Italic",
    "Times-Roman",
    "ZapfDingbats",
)


def glyph_map(path: Path) -> dict[str, str]:
    result = {}
    for raw in path.read_text(encoding="ascii").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        name, values = line.split(";", 1)
        result[name] = "".join(chr(int(value, 16)) for value in values.split())
    return result


def parse_afm(path: Path, names: dict[str, str], zapf: dict[str, str]):
    fields = {}
    widths = {}
    for raw in path.read_text(encoding="ascii").splitlines():
        line = raw.strip()
        if line.startswith("FontName ") or line.startswith("ItalicAngle "):
            key, value = line.split(None, 1)
            fields[key] = value
        elif (
            line.startswith("FontBBox ")
            or line.startswith("Ascender ")
            or line.startswith("Descender ")
            or line.startswith("CapHeight ")
        ):
            key, value = line.split(None, 1)
            fields[key] = value
        elif line.startswith("C "):
            parts = {key: value.strip() for key, value in re.findall(r"([A-Z]+) ([^;]+)", line)}
            glyph_name = parts.get("N")
            if glyph_name is None:
                continue
            if path.stem == "Symbol":
                text = names.get(glyph_name, "")
            else:
                text = (zapf if path.stem == "ZapfDingbats" else names).get(glyph_name, "")
            if len(text) == 1:
                widths[ord(text)] = float(parts["WX"])
    return fields, widths


def go_float(value: float) -> str:
    return f"{value:g}"


def generate(metrics, zapf_widths, package: str) -> str:
    lines = [
        "// Code generated by scripts/generate_core14_metrics.py; DO NOT EDIT.",
        "",
        f"package {package}",
        "",
        "type StandardFontMetric struct {",
        "\tascent float64",
        "\tdescent float64",
        "\thasAscent bool",
        "\thasDescent bool",
        "\tcapHeight float64",
        "\tflags int",
        "\tbbox [4]float64",
        "\titalicAngle float64",
        "\twidths map[rune]float64",
        "}",
        "",
        "var standardFontMetrics = map[string]StandardFontMetric{",
    ]
    for name in FONT_NAMES:
        fields, widths = metrics[name]
        bbox = [float(value) for value in fields["FontBBox"].split()]
        flags = 64 if name.startswith("Courier") else 0
        lines.extend([
            f'\t"{name}": {{',
            f'\t\tascent: {go_float(float(fields.get("Ascender", bbox[3])))}, descent: {go_float(float(fields.get("Descender", bbox[1])))},',
            f'\t\thasAscent: {str("Ascender" in fields).lower()}, hasDescent: {str("Descender" in fields).lower()},',
            f'\t\tcapHeight: {go_float(float(fields.get("CapHeight", 0)))}, flags: {flags},',
            f'\t\tbbox: [4]float64{{{", ".join(go_float(value) for value in bbox)}}},',
            f'\t\titalicAngle: {go_float(float(fields["ItalicAngle"]))},',
            "\t\twidths: map[rune]float64{",
        ])
        for codepoint in sorted(widths):
            lines.append(f"\t\t\t{codepoint}: {go_float(widths[codepoint])},")
        lines.extend(["\t\t},", "\t},"])
    lines.extend(["}", "", "var zapfDingbatsWidths = map[byte]float64{"])
    for codepoint in sorted(zapf_widths):
        lines.append(f"\t{codepoint}: {go_float(zapf_widths[codepoint])},")
    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-dir", type=Path, default=ROOT / "scripts/data/core14")
    parser.add_argument("--glyphlist", type=Path, default=ROOT / "scripts/data/glyphlist.txt")
    parser.add_argument("--zapf-glyphlist", type=Path, default=ROOT / "scripts/data/zapfdingbats.txt")
    parser.add_argument("--output", type=Path, default=ROOT / "fontdata/standard_metrics_generated.go")
    parser.add_argument("--package", default="fontdata")
    args = parser.parse_args()
    names, zapf = glyph_map(args.glyphlist), glyph_map(args.zapf_glyphlist)
    metrics = {}
    zapf_widths = {}
    for name in FONT_NAMES:
        fields, widths = parse_afm(args.input_dir / f"{name}.afm", names, zapf)
        metrics[name] = (fields, widths)
        if name == "ZapfDingbats":
            for raw in args.input_dir.joinpath(f"{name}.afm").read_text(encoding="ascii").splitlines():
                if raw.startswith("C "):
                    parts = {key: value.strip() for key, value in re.findall(r"([A-Z]+) ([^;]+)", raw)}
                    if parts.get("C", "").isdigit() and int(parts["C"]) >= 0:
                        zapf_widths[int(parts["C"])] = float(parts["WX"])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(metrics, zapf_widths, args.package), encoding="utf-8")


if __name__ == "__main__":
    main()
