#!/usr/bin/env python3
"""Generate PDF WinAnsi glyph mappings using Windows-1252 plus ISO overrides.

ISO 32000-1:2008 Annex D.2 assigns space to octal 240, hyphen to octal
255, and bullet to unused codes above octal 40. These PDF glyph assignments
differ from the corresponding Windows-1252 Unicode character assignments.
Reference: https://opensource.adobe.com/dc-acrobat-sdk-docs/standards/pdfstandards/pdf/PDF32000_2008.pdf
"""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "fontdata/winansi_encoding_generated.go"


def rune_literal(value: str) -> str:
    code = ord(value)
    if value == "'":
        return "'\\''"
    if value == "\\":
        return "'\\\\'"
    if 0x20 <= code < 0x7f:
        return f"'{value}'"
    if code <= 0xffff:
        return f"'\\u{code:04x}'"
    return f"'\\U{code:08x}'"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--package", default="fontdata")
    args = parser.parse_args()
    entries = {}
    for code in range(0x7f, 0x100):
        if code == 0x7f:
            entries[code] = "\u2022"
            continue
        try:
            text = bytes([code]).decode("cp1252")
        except UnicodeDecodeError:
            entries[code] = "\u2022"
            continue
        if len(text) == 1:
            entries[code] = text
    entries[0xa0] = " "
    entries[0xad] = "-"
    lines = [
        "// Code generated by scripts/generate_winansi_encoding.py; DO NOT EDIT.",
        "// Source: Windows-1252 codec with ISO 32000-1:2008 Annex D.2 glyph assignments.",
        "",
        f"package {args.package}",
        "",
        "var generatedWinAnsiEncoding = map[byte]rune{",
    ]
    for code, value in entries.items():
        lines.append(f"\t{code}: {rune_literal(value)},")
    lines.extend(["}", ""])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
